[project]
name = "ml-cloud-connector"
version = "2025.03.14.003"
description = "This tool is a ml cloud connector"
license = { file = "LICENSE" }
authors = [{ name = "HURIDOCS" }]
requires-python = ">= 3.10"


[project.urls]
HURIDOCS = "https://huridocs.org"
GitHub = "https://github.com/huridocs/ml-cloud-connector"