[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm[toml]>=7.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ml-cloud-connector"
dynamic = ["version"]
description = "This tool is a ml cloud connector"
license = { file = "LICENSE" }
authors = [{ name = "HURIDOCS" }]
requires-python = ">= 3.10"
dependencies = [
    "python-dotenv==1.0.1",
    "python-crontab==3.2.0",
    "google-cloud-compute==1.30.0",
    "httpx==0.28.1",
    "google-api-python-client==2.145.0",
    "pydantic==2.12.5",
    "setuptools==84.0.0",
    "requests==2.32.3",
    "protobuf==6.33.5",
    "google-cloud-storage==3.1.0",
    "graypy==2.1.0"
]

[project.urls]
HURIDOCS = "https://huridocs.org"
GitHub = "https://github.com/huridocs/ml-cloud-connector"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"
write_to = "_version.py"